### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good! Please close and prepare a final PR.

**Comment by mulkieran** [comment]
> Looks good! Please close and prepare a final PR.

Actually, could you fix the lint and bump the recommended development toolchain to 1.48 as well?

**Comment by jbaublitz** [comment]
Okay this should be ready for review again.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good. Please close and open for final review.

**Comment by jbaublitz** [comment]
Okay! I'm going to merge without review.

**Pull request closed without merging**
